### ISSUE TITLE
List of all authors and translators in the AUTHORS file

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/SURFER-Galleries#14]

**Comment by danielramosg** [comment]
Hi, we have now all the translators on the list. 
I can contact all of them and ask them to accept a CLA (Contributor License Agreement) so that they release the translation under a CC BY 4.0 International License.

Should I just write a short text and ask them to print-scan-send it? 
Should it be written by our lawyer?
Do we even need their signature or it is just fine to notify them by email and ask if they agree?

**Comment by porst17** [comment]
Fixed in 3bd49b55db7213d5fc9e8fd08464b024f4b745c9.

Using CLAs or not is a different issue and has to be discussed separately.

**Comment by danielramosg** [comment]
Discussion about CLAs opened in issue #32.
