### ISSUE TITLE
Arabic translation - italics don't seem to work with DejaVu, not tested for other font

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/SURFER-Galleries#24]
When compiling, all \emph, \it, or \textit commands with Arabic text to be italicised does not seem to work. Instead my pdf displays square brackets. 
Also texmaker seems to display some odd characters here and there, but they don't appear in the resulting pdf text (as far as I can tell), so the utf-8 format seems ok. Also XeTex is able to compile everything. 
P.S. ignore the files with ??? and untranslated file, this hopefully will be resolved tomorrow by the translator.

**Comment by porst17** [comment]
There seems to be some problem with the `DejaVu Sans Oblique` font set. Either the font does not contain Arabic letters or there is some problem with the font tables in this font. At least this is what the error message suggests. Since the oblique font type looks pretty much like a slanted font, I just worked around the issue by changing
```
\newfontfamily\arabicfont[Script=Arabic]{DejaVu Sans}
```
to
```
\newfontfamily\arabicfont[Script=Arabic, AutoFakeSlant]{DejaVu Sans Condensed}
```
Note that I also changed to the condensed font. The stroke width of the Arabic characters now almost match that of the Roman characters.
